### ISSUE TITLE
2D convolution with user_function

### ISSUE THREAD

**Issue by smartalecH** [smartalecH/meep_adjoint_simple#3]
A common task with practical inverse design is to "filter" the design region with a gaussian kernel so that the resulting geometry is smoothed. This is one of many ways to implement a minimum feature size constraint.

Accomplishing this with meep's user interface seems tricky. While material functions make it easy to "continuously" modify the permittivity profile of a geometry with position, it only accesses one point at a time. Consequently, functions like filters (or any other integrating function) can't be used because they require feedback/feedforward terms.

One solution could leverage a special material function that provides the user with an array of all the points it plans to fill. The user can then supply an array with the post-processed values corresponding to these points. This is similar to the user_file feature, but without the interpolation (which would defeat the whole purpose). Maybe there's an easy fix that I'm missing?

@oskooi @stevengj @HomerReid @danielwboyce

**Comment by smartalecH** [comment]
I'm able to circumvent the issue by filtering the parameters, rather than the actual permittivity values (as we discussed). However, if I simulate a higher density of design parameters than meep pixels, there are several gradients that go to zero. This seems intuitively correct, but the finite-difference gradients are not zero. They are typically 6 orders of magnitide smaller than similar simulations when I don't oversample my design space. Is this neglibible? Or is there something else we should be aware of?

**Comment by stevengj** [comment]
Seems fine to me, but it seems like in practice you will always use a filter radius that is larger than a Meep pixel, in which case no gradients should vanish.

**Comment by smartalecH** [comment]
Good point, thanks!
